name: 'time_logger'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'time_logger'

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  time_logger:
    +materialized: view
  
    marts:
      +materialized: table
      
    staging:
      +materialized: ephemeral
      +schema: 'staging'